version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - ${installDir}/config:/config
      - ${installDir}/data:/opt/valheim
    ports: 
      - "${PORT}:${PORT}/udp"
      - "${WSPORT}:${WSPORT}/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
